language: node_js
node_js:
  - "11.0"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/frontend/node_modules
before_script:
  - npm i -g @angular/cli
script:
  - cd frontend
  - npm install
  - npm run lint
  - ng test --watch=false  --code-coverage --source-map
  - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then npm run build --prod --base-href="/workflow/"; fi 
  - if [[ "$TRAVIS_BRANCH" != "master" ]] ; then npm run build --prod; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/ui
  on:
    branch: master
